environment:
 github_release_token:
  secure: TTQbwwwftUsijup2DaIPSnfBoYtXNrPVUFxNdFF/kugUndKeQk2k7YUSe1C1ojZn
 matrix:
  - nodejs_version: 5
  - nodejs_version: 6
  - nodejs_version: 7
  - nodejs_version: 8

platform:
  - x86
  - x64

image: Visual Studio 2015

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install -g npm
  - node --version
  - npm --version
  - git submodule update --init --recursive

build_script:
  - npm install --build-from-source

test_script:
  - npm test

after_test:
  - node_modules/.bin/node-pre-gyp package

artifacts:
  - path: build\stage\gagern\node-libtidy\releases\download\**\*.tar.gz
    name: binary

deploy:
  - provider: GitHub
    release: $(APPVEYOR_REPO_TAG_NAME)
    artifact: binary
    auth_token: $(github_release_token)
    draft: true
    prerelease: false
    on:
      appveyor_repo_tag: true

after_deploy:
  - git clean -fdx
  - npm install --fallback-to-build=false
  - npm test
